### ISSUE TITLE
Unknown configuration section 'sshfs'.

### ISSUE THREAD

**Issue by Ziemowit** [fabiokr/vagrant-sshfs#40]
Vagrant version is 1.8.1.
Plugin vagrant-sshfs is installed:

**vagrant plugin list**

```
vagrant-share (1.1.5, system)
vagrant-sshfs (1.0.0)
```

Appropriate lines are added:

```
Vagrant.configure("2") do |config|
  # always use Vagrants insecure key
  config.ssh.insert_key = false

  # vagrant-sshfs - start of configuration
  config.sshfs.username = "some_user"
  config.sshfs.paths = { "xxx" => "yyy" }
  # vagrant-sshfs - end of configuration
....
```

But when I run: **vagrant reload** I receive:

```
There are errors in the configuration of this machine. Please fix
the following errors and try again:

Vagrant:
* Unknown configuration section 'sshfs'.
```

Is it some kind of bug or did I miss sth?

**Comment by railsbros-dirk** [comment]
I just ran into the same issue.

As it turns out there was maybe a contributor change or something else. Anyway, if you install `vagrant-sshfs` after 14th March you will **not** get this one but https://github.com/dustymabe/vagrant-sshfs. It seems it a complete rewrite and works entirely different.

I don't know why it is still called `vagrant-sshfs` and is published as the [same gem on Rubygems](https://rubygems.org/gems/vagrant-sshfs). But this is a big problem IMO.

Maybe @fabiokr and @dustymabe can help out?

As a workaround install the _old_ version:

```
vagrant plugin install vagrant-sshfs --plugin-version 0.0.8
```

**Comment by tisba** [comment]
Looks like something got messed up here quite a lot. Is there any way to install a specific gem as a Vagrant plugin?

**Comment by Ziemowit** [comment]
Solution provided by @railsbros-dirk solved my problem. Right now I have issue with:

`/opt/vagrant/embedded/lib/ruby/2.2.0/fileutils.rb:252:in `mkdir': Permission denied @ dir_s_mkdir - /home/core (Errno::EACCES)
`
but I think it is not a bug but rather problem related to my settings.
Thank you!

**Comment by Ziemowit** [comment]
Ok I have solved 2nd issue. Hmmm in fact I could close this ticket... But it may be helpful for future user to get some feedback from the creator why installation from this sites download sth different to Vagrant.

**Comment by dustymabe** [comment]
Hi, @railsbros-dirk @Ziemowit @tisba

I rewrote the sshfs plugin to be a synced folder implementation. Fabio allowed me to submit the new implementation with a major version change. The hope is that we might be able to get this "synced folder" implementation back into vagrant core at some point as a supported synced folder transport. 

The new code is here: https://github.com/dustymabe/vagrant-sshfs

Can you try to use the new implementation and see if you can get it working for you? If there are things that don't work can you open an issue on the github and I can try to get those fixed. Sorry the change happened unexpectedly. There wasn't really any good way (that I know of) to communicate this change to the users.

**Comment by Ziemowit** [comment]
Hmmm I think the best would be to put this information at the beginning of README.md here :P

**Comment by dustymabe** [comment]
@Ziemowit. I agree. I assumed people would look at the new repo though. I do have some reference to it in the *History* section [there](https://github.com/dustymabe/vagrant-sshfs#history)

I can submit at PR to this repo to add the same information.

**Comment by tisba** [comment]
Too bad that this plugin will now be abandoned. We require a solid performance and were using fabiokr/vagrant-sshfs because it was the only viable approach that worked :-/

**Comment by dustymabe** [comment]
Hi @tisba. It's the same technology (sshfs) underneath. Can you help me understand why the new plugin doesn't satisfy the performance requirement?

I have plans to pretty much enable any mount option to be provided by the user so theoretically you can do anything that you could with sshfs native (or with fabiokr/vagrant-sshfs). The issue for that is https://github.com/dustymabe/vagrant-sshfs/issues/5

**Comment by tisba** [comment]
Maybe I misunderstood the README

> It does this by executing the SSHFS client software within the guest, which creates and SSH connection from the Vagrant guest back to the Vagrant host.

This would mean, that the guest mounts a folder from the host. Which leads to undesired performance hit, when the guest is working intensively with the mounted volume. What we do the opposite and create the mount from the host into the guest. Which works perfectly in terms of editing code etc and the guest has a just a bunch of local files to work with and no perf hit because of the remote sshfs volume.

I did not spot dustymabe/vagrant-sshfs#5 before, sorry. This might fix the issue then, I guess.

**Comment by dustymabe** [comment]
> This would mean, that the guest mounts a folder from the host.

Ahh.. I see what you mean now. You are correct in that "the host folder is mounted into the guest". I don't believe issue #5 with solve that problem. 

@tisba have opened https://github.com/dustymabe/vagrant-sshfs/issues/7 as a place where we can discuss and evaluate this use case. Do you mind adding your input there? I may try to propose alternative solutions and I'd like for you to credit or discredit them as we go.
